=begin
#CommaFeed API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AdminApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AdminApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AdminApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdminApi' do
    it 'should create an instance of AdminApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AdminApi)
    end
  end

  # unit tests for admin_delete_user
  # Delete a user
  # Delete a user, and all his subscriptions
  # @param id_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'admin_delete_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for admin_get_user
  # Get user information
  # Get user information
  # @param id user id
  # @param [Hash] opts the optional parameters
  # @return [UserModel]
  describe 'admin_get_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for admin_get_users
  # Get all users
  # Get all users
  # @param [Hash] opts the optional parameters
  # @return [Array<UserModel>]
  describe 'admin_get_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for admin_save_user
  # Save or update a user
  # Save or update a user. If the id is not specified, a new user will be created
  # @param admin_save_user_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'admin_save_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_metrics
  # Retrieve server metrics
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_metrics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
