=begin
#CommaFeed API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::FeedEntriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FeedEntriesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::FeedEntriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeedEntriesApi' do
    it 'should create an instance of FeedEntriesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::FeedEntriesApi)
    end
  end

  # unit tests for get_tags
  # Get list of tags for the user
  # Get list of tags for the user
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_entries
  # Mark multiple feed entries
  # Mark feed entries as read/unread
  # @param multiple_mark_request Multiple Mark Request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'mark_entries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_entry
  # Mark a feed entry
  # Mark a feed entry as read/unread
  # @param mark_request Mark Request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'mark_entry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for star_entry
  # Star a feed entry
  # Mark a feed entry as read/unread
  # @param star_request Star Request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'star_entry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tag_entry
  # Set feed entry tags
  # @param tag_request Tag Request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'tag_entry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
