=begin
#CommaFeed API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for CommafeedClient::UsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @api_instance = CommafeedClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@api_instance).to be_instance_of(CommafeedClient::UsersApi)
    end
  end

  # unit tests for delete_user
  # Delete the user account
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_profile
  # Retrieve user&#39;s profile
  # @param [Hash] opts the optional parameters
  # @return [UserModel]
  describe 'get_user_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_settings
  # Retrieve user settings
  # Retrieve user settings
  # @param [Hash] opts the optional parameters
  # @return [Settings]
  describe 'get_user_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for password_recovery_callback
  # @param email 
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'password_recovery_callback test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for register_user
  # Register a new account
  # @param registration_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'register_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for save_user_profile
  # Save user&#39;s profile
  # @param profile_modification_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'save_user_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for save_user_settings
  # Save user settings
  # Save user settings
  # @param settings 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'save_user_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_password_reset
  # send a password reset email
  # @param password_reset_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'send_password_reset test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
