=begin
#CommaFeed API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CommafeedClient::FeedInfoRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CommafeedClient::FeedInfoRequest do
  let(:instance) { CommafeedClient::FeedInfoRequest.new }

  describe 'test an instance of FeedInfoRequest' do
    it 'should create an instance of FeedInfoRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(CommafeedClient::FeedInfoRequest)
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
