=begin
#CommaFeed API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

# Common files
require 'commafeed/api_client'
require 'commafeed/api_error'
require 'commafeed/version'
require 'commafeed/configuration'

# Models
require 'commafeed/models/add_category_request'
require 'commafeed/models/admin_save_user_request'
require 'commafeed/models/category'
require 'commafeed/models/category_modification_request'
require 'commafeed/models/collapse_request'
require 'commafeed/models/entries'
require 'commafeed/models/entry'
require 'commafeed/models/feed_info'
require 'commafeed/models/feed_info_request'
require 'commafeed/models/feed_modification_request'
require 'commafeed/models/id_request'
require 'commafeed/models/mark_request'
require 'commafeed/models/multiple_mark_request'
require 'commafeed/models/password_reset_request'
require 'commafeed/models/profile_modification_request'
require 'commafeed/models/registration_request'
require 'commafeed/models/server_info'
require 'commafeed/models/settings'
require 'commafeed/models/sharing_settings'
require 'commafeed/models/star_request'
require 'commafeed/models/subscribe_request'
require 'commafeed/models/subscription'
require 'commafeed/models/tag_request'
require 'commafeed/models/unread_count'
require 'commafeed/models/user_model'

# APIs
require 'commafeed/api/admin_api'
require 'commafeed/api/feed_categories_api'
require 'commafeed/api/feed_entries_api'
require 'commafeed/api/feeds_api'
require 'commafeed/api/server_api'
require 'commafeed/api/users_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
